#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

export DEVMEMORY_CHAT_PROVIDER="${DEVMEMORY_CHAT_PROVIDER:-ollama}"
export DEVMEMORY_EMBEDDING_PROVIDER="${DEVMEMORY_EMBEDDING_PROVIDER:-ollama}"
export DEVMEMORY_VECTOR_STORE="${DEVMEMORY_VECTOR_STORE:-qdrant}"

export DEVMEMORY_OLLAMA_ENDPOINT="${DEVMEMORY_OLLAMA_ENDPOINT:-http://localhost:11434}"
export DEVMEMORY_OLLAMA_CHAT_MODEL="${DEVMEMORY_OLLAMA_CHAT_MODEL:-llama3.2}"
export DEVMEMORY_OLLAMA_EMBEDDING_MODEL="${DEVMEMORY_OLLAMA_EMBEDDING_MODEL:-nomic-embed-text}"

export DEVMEMORY_QDRANT_ENDPOINT="${DEVMEMORY_QDRANT_ENDPOINT:-http://localhost:6333}"
export DEVMEMORY_QDRANT_COLLECTION="${DEVMEMORY_QDRANT_COLLECTION:-devmemory_memories}"

dotnet run --project "$ROOT_DIR/src/DevMemory.Cli" -- ai-doctor